- name: Install nginx and deploy HTML
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy custom index.html
      copy:
        content: "<h1>Hello from Terraform + Ansible!</h1>"
        dest: /var/www/html/index.html